const express = require('express')
const mainRouters = require('./src/routes')
const connectDB = require('./src/databases/config')
const colors = require('colors')
const dotenv = require('dotenv')
const app = express()
app.use(express.json({ limit: '50mb' }))
dotenv.config()
connectDB()
mainRouters(app)
app.listen(process.env.PORT, () => {
    console.log(`Example app listening at http://localhost:${process.env.PORT}`)
})